### ISSUE TITLE
`structure` option is inconsistent with its use in pinny

### ISSUE THREAD

**Issue by vmarta** [mobify/navitron#2]
The use of the `structure` option in navitron is opposite of the one in [pinny](https://github.com/mobify/pinny#structure). Here you set it to _true_ for your own custom markup, whereas you set it to _false_ in pinny to do the same thing.

(FYI, I was looking at the 'testing' branch)

**Comment by mlworks** [comment]
Thanks for the feedback @vmarta ! Fixed the issue here: https://github.com/mobify/navitron/commit/07ce2ab40fbfe3d1db8542500f2cb815707a832d

Closing issue.
