### ISSUE TITLE
.gitignore and the dist/ folder

### ISSUE THREAD

**Issue by vmarta** [mobify/navitron#4]
Branch: testing

Let's not ignore the dist/ folder in the [.gitignore](https://github.com/mobify/navitron/blob/testing/.gitignore) file. Because we'll want to update and commit the dist files.

**Comment by mlworks** [comment]
Thank for the feedback @vmarta !  See commit: https://github.com/mobify/navitron/commit/3eaa031d200c132cb063472a14bc9fbe01ca824a for fix. Closing issue.
